[package]
name = "extract-metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
swf = "0.2.2"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
walkdir = "2"